use_frameworks!

platform :ios, '10.0'

target 'VisitHealthPackage_Example' do
  pod 'VisitHealthPackage', :path => '../'

  target 'VisitHealthPackage_Tests' do
    inherit! :search_paths

    
  end
end
